---
- name: Prepare
  hosts: instance
  gather_facts: false
  tasks:
    - name: Install tools on Alpine
      ansible.builtin.command: apk add --no-cache tar gzip skopeo
      changed_when: true

    - name: "Download sample redis image (Image is created by podman)"
      ansible.builtin.get_url:
        url: "{{ push_image_to_registry_generic_secret_sample_image_by_podman_url }}"
        dest: "/tmp/redis-podman.tar.gz"
        headers:
          X-Appwrite-Project: "{{ push_image_to_registry_generic_secret_api_key }}"
          X-Appwrite-Key: "{{ push_image_to_registry_generic_secret_api_secret }}"
        mode: "0644"

    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "/tmp/redis-podman"
        state: directory
        mode: "0755"

    - name: Extract the downloaded tar file
      ansible.builtin.unarchive:
        src: "/tmp/redis-podman.tar.gz"
        dest: "/tmp/redis-podman"
        remote_src: true
        mode: "0755"
