---
driver:
  name: docker

ansible:
  executor:
    backend: ansible-playbook

provisioner:
  name: ansible
  config_options:
    defaults:
      # Uses the absolute path of your project to safely find the roles folder
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
  inventory:
    group_vars:
      all:

platforms:
  - name: sftp-srv
    image: atmoz/sftp
    command: "foo:pass:::upload"
    privileged: false
  - name: instance
    image: docker.io/alpine:3.23.3
    privileged: false

scenario:
  name: fetch_files_sftp
  test_sequence:
    - create
    - prepare
    - converge
    - verify
    - destroy
