---
driver:
  name: docker

ansible:
  executor:
    backend: ansible-playbook

provisioner:
  name: ansible
  config_options:
    defaults:
      # Uses the absolute path of your project to safely find the roles folder
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
      gathering: smart
      fact_caching: jsonfile
      fact_caching_connection: /tmp/molecule_facts_cache
      fact_caching_timeout: 7200
  inventory:
    group_vars:
      all:
        gitlab_push_repository_var_repo_url: "gitlab.com/cd-cluster/write-repository-molecule-test.git"
        gitlab_push_repository_secret_pat: "${gitlab_push_repository_secret_pat}"

platforms:
  - name: instance
    image: docker.io/alpine:3.23.3
    privileged: false

scenario:
  name: gitlab-clone-repository
  test_sequence:
    - create
    - prepare
    - converge
    - verify
    - destroy
