# defaults/main.yml
---
fetch_files_sftp_username: ""
fetch_files_sftp_sftp_ip: ""
fetch_files_sftp_sftp_password: ""

fetch_files_sftp_file_path_src: ""
fetch_files_sftp_file_path_dest: ""
fetch_files_sftp_strict_host_key_checking: false

fetch_files_sftp_connect_timeout: 5
fetch_files_sftp_connection_attempts: 1
