---
name: Molecule & Python Test

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "**"        # Matches all branches including those with slashes (e.g., feature/test)
  pull_request:
    branches:
      - "**"

jobs:
  unit-galaxy:
    name: Run Unit Tests
    uses: ansible/ansible-content-actions/.github/workflows/unit.yaml@main

  integration:
    name: Run Integration Tests
    uses: ansible/ansible-content-actions/.github/workflows/integration.yaml@main

  molecule:
    name: Run Molecule Tests
    runs-on: ubuntu-latest

    env:
      gitlab_clone_repository_secret_pat: ${{ secrets.gitlab_clone_repository_secret_pat }}
      gitlab_push_repository_secret_pat: ${{ secrets.gitlab_push_repository_secret_pat }}
      sample_image_created_by_cosign_url: ${{ secrets.sample_image_created_by_cosign_url }}
      s3_api_key: ${{ secrets.s3_api_key }}
      s3_api_secret: ${{ secrets.s3_api_secret }}
      gitlab_registry_token: ${{ secrets.gitlab_registry_token }}
      sample_image_created_by_podman_url: ${{ secrets.sample_image_created_by_podman_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-dev-tools
          pip3 install molecule-plugins[docker]

      - name: Install Ansible dependencies
        run: |
          ansible-galaxy collection install -r test-requirements.yml

      - name: Install System dependencies
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Run Molecule Tests
        run: molecule test --all
