---
name: Molecule Test

on:
  push:
    branches:
      - "**"        # Matches all branches including those with slashes (e.g., feature/test)
  pull_request:
    branches:
      - "**"

jobs:
  molecule:
    name: Run Molecule Tests
    runs-on: ubuntu-latest

    env:
      gitlab_clone_repository_secret_pat: ${{ secrets.gitlab_clone_repository_secret_pat }}
      gitlab_push_repository_secret_pat: ${{ secrets.gitlab_push_repository_secret_pat }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-dev-tools
          pip3 install molecule-plugins[docker]

      - name: Install Ansible dependencies
        run: |
          ansible-galaxy collection install -r test-requirements.yml

      - name: Install System dependencies
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Run Molecule Tests
        run: molecule test --all
